server:
  port: 8088
  address: 0.0.0.0

spring:
  cloud:
    nacos:
      discovery:
        prefer-ip-address: true
        ip: 10.140.156.5
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 127.0.0.1 # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      password: Evan828828 # Redis 服务器连接密码（默认为空）
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接
  mail:
    host: smtp.163.com           # 根据你的邮箱替换
    port: 465                   # 465 走 SSL；如果用 587 就把 ssl 关掉，开 starttls
    username: syf17757189184@163.com
    password: PXZkS37t5taGbA4p   # 授权码/专用密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true        # 端口 465 时 true
          starttls:
            enable: false       # 端口 587 时 true
            required: false
mail:
  from: syf17757189184@163.com
